function plotFrame(origin, roll, pitch, yaw)
R_z = rotationMatrix3d(yaw, 'z');
R_y = rotationMatrix3d(pitch, 'y');
R_x = rotationMatrix3d(roll, 'x');

R = R_z * R_y * R_x;

x = R * [0.1; 0; 0];
y = R * [0; 0.1; 0];
z = R * [0; 0; 0.1];

plot3([origin(1), origin(1) + x(1)], ...
    [origin(2), origin(2) + x(2)], ...
    [origin(3), origin(3) + x(3)], ...
    'red', 'LineWidth', 2), hold on;
plot3([origin(1), origin(1) + y(1)], ...
    [origin(2), origin(2) + y(2)], ...
    [origin(3), origin(3) + y(3)], ...
    'green', 'LineWidth', 2), hold on;
plot3([origin(1), origin(1) + z(1)], ...
    [origin(2), origin(2) + z(2)], ...
    [origin(3), origin(3) + z(3)], ...
    'blue', 'LineWidth', 2), hold on;
end
